CREATE DATABASE vegetables;

CREATE TABLE public.names {
	id SERIAL NOT NULL PRIMARY KEY,	
	vegetable.name VARCHAR(30) NOT NULL,
	description VARCHAR(200) NOT NULL 
};

CREATE TABLE public.days {
	id SERIAL NOT NULL PRIMARY KEY,
	day VARCHAR(20) NOT NULL
};

CREATE TABLE public.users {
	id SERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	display_name VARCHAR(100) NOT NULL
	};

CREATE TABLE public.meals {
	id SERIAL NOT NULL PRIMARY KEY,
	meal VARCHAR(15) NOT NULL
};